apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: team4project3
  name: cl-be
  labels:
    app: cl-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cl-be
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: cl-be
    spec:
      serviceAccountName: catus-locatus
      containers:
        - name: backend-t4p3
          image: team4amazingregistry.azurecr.io/backend-t4p3:latest
          resources: {}
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
          envFrom:
            - secretRef:
                name: catus-locatus-secrets
          livenessProbe:
            httpGet:
              path: /api/health
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 4001
            initialDelaySeconds: 5
            periodSeconds: 15
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "team4-super-secrets"
